# Spacemacs Alacritty Colors
# Default colors
[colors.primary]
background = '#292b2e'
foreground = '#b2b2b2'

#[colors.cursor]
#cursor = '#3760bf'
#text = '#e1e2e7'

# Normal colors
[colors.normal]
black = '#292b2e'
red = '#f2241f'
green = '#67b11d'
yellow = '#b1951d'
blue = '#4f97d7'
magenta = '#a31db1'
cyan = '#28def0'
white = '#b2b2b2'

# Bright colors
[colors.bright]
black = '#655370'
red = '#f2241f'
green = '#67b11d'
yellow = '#b1951d'
blue = '#3a81c3'
magenta = '#a31db1'
cyan = '#21b8c7'
white = '#fbf8ef'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#b1951d'

[[colors.indexed_colors]]
index = 17
color = '#f2241f'

[cursor]
blink_interval = 550
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12

[font.bold]
family = "Intel One Mono"
style = "Bold"

[font.bold_italic]
family = "Intel One Mono"
style = "Bold Italic"

[font.italic]
family = "Intel One Mono"
style = "Italic"

[font.normal]
family = "Intel One Mono"
style = "Regular"

[window]
opacity = 0.9
