local newline = require('snippet_utils').newline

return {
  -- normal snippets
},
  {
    -- auto snippets
    s('tp', {
      t({
        '\\documentclass[12pt]{article}',
        '\\usepackage{fontspec}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage[title]{appendix}',
        '\\usepackage{titlesec}',
        '\\usepackage[bookmarks]{hyperref}',
        '\\usepackage[indent=15pt]{parskip}',
        '\\usepackage{enumitem}',
        '\\usepackage[table]{xcolor}',
        '\\usepackage{ctable}',
        '\\usepackage{multirow}',
        '\\usepackage[indent=15pt]{parskip}',
        '\\usepackage{geometry}',
        '\\usepackage{graphicx}',
        '\\usepackage[en-GB]{babel}',
        '\\usepackage[backend=biber,style=',
      }),
      i(1, 'apa'),
      t(']{biblatex}'),
      newline(''),
      t({
        '\\usepackage{csquotes}',
        '\\usepackage{siunitx}',
        '\\usepackage{hyperref}',
        '\\usepackage{subcaption}',
        '\\usepackage{svg}',
        '\\usepackage{import}',
        '\\usepackage{xifthen}',
        '\\usepackage{pdfpages}',
        '\\usepackage{transparent}',
        '\\newcommand{\\incfig}[1]{',
        '\\def\\svgwidth{\\columnwidth}',
        '\\import{}{#1.pdf_tex}',
        '}',
        '\\setmainfont{',
      }),
      i(2),
      t('}'),
      newline(''),
      t({
        '\\DeclareFieldFormat{apacase}{#1}',
        '\\DeclareLanguageMapping{english}{english-apa}',
        '\\DeclareCaptionFormat{custom}{',
        '\\texbf{#1#2}\\texit{\\small #3}',
        '}',
        '\\captionsetup{format=custom}',
        '\\addbibresource{',
      }),
      i(3, 'bib'),
      t('.bib}'),
      newline(''),
      newline(''),
      t({
        '\\geometry{',
        '  a4paper,',
        '  total={170mm,257mm},',
        '  left=20mm,',
        '  top=20mm,',
        '}',
        '',
        '\\begin{document}',
        '',
        '\\begin{titlepage}',
        '  \\vspace*{\\fill}',
        '  \\centering',
        '  \\LARGE ',
      }),
      i(4, 'Title'),
      t(' \\par'),
      newline(''),
      t({
        '  \\vspace{1cm}',
        '  \\large Ham Wen Hong \\par',
        '  \\vspace{0.1cm}',
        '  \\large 1171103503 \\par',
        '  \\vspace{0.1cm}',
        '  \\large Multimedia University \\par',
        '  \\vspace{0.5cm}',
        '  \\large ',
      }),
      i(5, 'Due Date'),
      t(' \\par'),
      newline(''),
      t({
        '  \\vspace*{\\fill}',
        '\\end{titlepage}',
        '',
        '',
      }),
      i(0),
      newline(''),
      t('\\end{document}'),
    }),
    s('tk', {
      t({
        '\\documentclass[convert={density=200,outext=.png}]{standalone}',
        '\\usepackage{tikz}',
        '\\usepackage{color}',
        '',
        '\\begin{document}',
        '\\begin{tikzpicture}',
        '  ',
      }),
      i(0),
      newline(''),
      t({
        '\\end{tikzpicture}',
        '\\end{document}',
      }),
    }),
    s('bmr', {
      t({
        '\\documentclass{beamer}',
        '\\usetheme{Warsaw}',
        '\\title[',
      }),
      i(0, 'Abbreviated Title'), t(']{'),
      i(1, 'Main Title'), t('}'),
      newline(''),
      t('\\subtitle{'), i(2, 'Subtitle'), t('}'),
      newline(''),
      t('\\author{'), i(3, 'Little Clover'), t('}'),
      newline(''),
      t('\\institute{'), i(4, 'FIST'), t('}'),
      t({
        '\\begin{document}',
        '\\begin{frame}',
        '\\titlepage',
        '\\end{frame}',
        '\\end{document}',
      })
    }),
    s('nfr', {
      t({
        '\\begin{frame}[t]{',
      }),
      i(0, 'Slide Title'), t('}\vspace{4pt}'),
      newline(''),
      i(1),
      t({
        '\\end{frame}',
      })
    }),
    s('begg', {
      t('\\begin{'),
      i(1),
      t('}'),
      i(0),
      newline(''),
      t('\\end{'),
      rep(1),
      t('}'),
    }),
    s('figg', {
      t('\\begin{figure}['),
      i(1, 'htpb'), t(']'),
      newline('  \\centering'),
      newline(''),
      i(2, '  \\includegrahics[width=0.8\\textwidth]'), t('{'),
      i(3), t('}'),
      newline('  \\caption{'), rep(3), t('}'),
      newline('  \\label{fig:'), rep(3), t('}'),
      newline('\\end{figure}'),
    }),
    s('tbl', {
      t('\\begin{minipage}{\\textwidth}'),
      newline(''),
      t('\\definecolor{'),
      i(1, 'LightGray'),
      t('}{gray}{0.95}'),
      newline(''),
      t('\\definecolor{'),
      i(2, 'DarkGray'),
      t('}{gray}{0.75}'),
      newline('\\bgroup'),
      t('\\setlength{\\tabcolsep}'),
      t('{'),
      i(3, '20pt'),
      t('}'),
      newline(''),
      t('\\def\\arraystretch{'),
      i(4, '2'),
      t('}%'),
      newline(''),
      t('{\\rowcolors{2}{'),
      rep(1),
      t('}{'),
      rep(2),
      t('}'),
      newline(''),
      t('\\begin{tabular}{'),
      i(5, 'cc'),
      t('}'),
      newline(''),
      t('  '),
      i(0),
      newline(''),
      t({
        '\\end{tabular}',
        '}',
        '\\egroup',
        '\\end{minipage}',
      }),
    }),
    s('enm', {
      t({
        '\\begin{enumerate}',
        '  \\item ',
      }),
      i(0),
      newline(''),
      t('\\end{enumerate}'),
    }),
    s('itz', {
      t({
        '\\begin{itemize}',
        '  \\item ',
      }),
      i(0),
      newline(''),
      t('\\end{itemize}'),
    }),
    s('dsc', {
      t({
        '\\begin{description}',
        '  \\item[',
      }),
      i(1),
      t('] '),
      i(0),
      newline(''),
      t('\\end{description}'),
    }),
  }
