local newline = require('snippet_utils').newline

return {
  -- normal snippets
},
  {
    -- auto snippets
    s('tp', {
      t({
        '\\documentclass[12pt]{article}',
        '\\usepackage{fontspec}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage[title]{appendix}',
        '\\usepackage{titlesec}',
        '\\usepackage[bookmarks]{hyperref}',
        '\\usepackage[indent=15pt]{parskip}',
        '\\usepackage{enumitem}',
        '\\usepackage{ctable}',
        '\\usepackage{multirow}',
        '\\usepackage[indent=15pt]{parskip}',
        '\\usepackage{geometry}',
        '\\usepackage{graphicx}',
        '\\usepackage[english]{babel}',
        '\\usepackage[backend=biber,style=',
      }),
      i(1, 'apa'),
      t(']{biblatex}'),
      newline(''),
      t({
        '\\usepackage{csquotes}',
        '\\usepackage{siunitx}',
        '\\usepackage{hyperref}',
        '\\DeclareFieldFormat{apacase}{#1}',
        '\\DeclareLanguageMapping{english}{english-apa}',
        '\\addbibresource{',
      }),
      i(2, 'bib'),
      t('.bib}'),
      newline(''),
      newline(''),
      t({
        '\\geometry{',
        '  a4paper,',
        '  total={170mm,257mm},',
        '  left=20mm,',
        '  top=20mm,',
        '}',
        '',
        '\\begin{document}',
        '',
        '\\begin{titlepage}',
        '  \\vspace*{\fill}',
        '  \\centering',
        '  \\LARGE ',
      }),
      i(3, 'Title'),
      t(' \\par'),
      newline(''),
      t({
        '  \\vspace{1cm}',
        '  \\large Ham Wen Hong \\par',
        '  \\vspace{0.1cm}',
        '  \\large 1171103503 \\par',
        '  \\vspace{0.1cm}',
        '  \\large Multimedia University \\par',
        '  \\vspace{0.5cm}',
        '  \\large ',
      }),
      i(4, 'Due Date'),
      t(' \\par'),
      newline(''),
      t({
        '  \\vspace*{\fill}',
        '\\end{titlepage}',
        '',
        '',
      }),
      i(0),
      newline(''),
      t('\\end{document}'),
    }),
    s('tk', {
      t({
        '\\documentclass[convert={density=200,outext=.png}]{standalone}',
        '\\usepackage{tikz}',
        '\\usepackage{color}',
        '',
        '\\begin{document}',
        '\\begin{tikzpicture}',
        '  ',
      }),
      i(0),
      newline(''),
      t({
        '\\end{tikzpicture}',
        '\\end{document}',
      }),
    }),
    s('bg', {
      t('\\begin{'),
      i(1),
      t('}'),
      i(0),
      newline(''),
      t('\\end{'),
      rep(1),
      t('}'),
    }),
    s('tb', {
      t('\\begin{minipace}{\\textwidth}'),
      newline(''),
      t('\\definecolor{'),
      i(1, 'LightGray'),
      t('{gray}{0.95}'),
      newline(''),
      t('\\definecolor{'),
      i(2, 'DarkGray'),
      t('{gray}{0.75}'),
      newline('\\bgroup'),
      t('\\setlength{\\tabcolsep{'),
      i(3, '20pt'),
      t('}'),
      newline(''),
      t('\\def\\arraystretch{'),
      i(4, '2'),
      t('}%'),
      newline(''),
      t('{\\rowcolors{2}{'),
      rep(1),
      t('}{'),
      rep(2),
      t('}'),
      newline(''),
      t('\\begin{tabular}{'),
      i(5, 'cc'),
      t('}'),
      newline(''),
      t('  '),
      i(0),
      newline(''),
      t({
        '\\end{tabular}',
        '}',
        '\\egroup',
        '\\end{minipage}',
      }),
    }),
    s('enr', {
      t({
        '\\begin{enumerate}',
        '  \\item ',
      }),
      i(0),
      newline(''),
      t('\\end{enumerate}'),
    }),
    s('itz', {
      t({
        '\\begin{itemize}',
        '  \\item ',
      }),
      i(0),
      newline(''),
      t('\\end{itemize}'),
    }),
    s('dsc', {
      t({
        '\\begin{description}',
        '  \\item[',
      }),
      i(1),
      t('] '),
      i(0),
      newline(''),
      t('\\end{description}'),
    }),
  }
